services:
  - type: web
    name: applisync-backend
    env: docker
    dockerFilePath: backend/Dockerfile
    dockerContext: backend
    plan: free
    envVars:
      - key: GROQ_API_KEY
        value: gsk_3TfjBJ8qKOAZAiADifCwWGdyb3FYoe2H6tYy0TiZolV5CW2m
      - key: PORT
        value: 10000
